### ISSUE TITLE
Possibility of specifying other values for GPC signal

### ISSUE THREAD

**Issue by coolharsh55** [globalprivacycontrol/gpc-spec#22] opened 2021-07-18 09:47 UTC
The [spec mentions](https://globalprivacycontrol.github.io/gpc-spec/#the-sec-gpc-header-field-for-http-requests) the value of GPC to be: 
> A user agent MUST generate a Sec-GPC header field with a field-value that is exactly the numeric character "1" if the user's Global Privacy Control preference is set. 

It does not specify: 

(a) What should be the value if GPC is _not set_. IMO the 'absence' of GPC and GPC being explicitly turned off should be two different values to not conflate having set (some state of) GPC as opposed to not having GPC (supported) by the user-agent. This can be done through, e.g. `Sec-GPC: 0`

(b) If other values of GPC can be set and supported, such as in future specs, to indicate other interpretations or conditions for use of GPC. Through such additional values, GPC can become capable of specifying multiple 'preferences' - such as for different conditions, jurisdictions, or additional restrictions.

**Comment by pes10k** [comment] 2021-07-21 20:47
Hello!

a) Since GPC is about asserting an opt-in privacy right, I dont know if an option to express a "my browser knows about GPC but i don't want to assert the rights behind it" preference is useful.  As regards to site behavior, I expect a `Sec-GPC: 0` value would be the same thing as sending nothing.    If a site wants to know that the user turned off GPC in response to the page's request, they can already do though a session cookie (or similar) and seeing that the GPC signal is no longer sent.

Adding a third state thought to GPC (not sent, sent and 1, and / or sent and 0) adds fingerpritning surface, so unless there is a practical benefit to it, im still in favor of the current description.

Is there a use case you have in mind that wouldn't be possible for a site to capture otherwise?

b) By design, other GPC values are not supported.  This is by design, since turning into GPC into a preferece-broadcasting system would have significant risks in the short term (e.g., increased fingerprinting surface) and longer term (e.g., turning GPC into a system where browsers are expected to advertise the privacy preferences their local jurisdiction entitles them to, which would be very bad privacy wise.  A privacy feature that requires me to advertise my location to get privacy is a deeply flawed privacy system.

Hope this helps explain the design of GPC!  Im going to close the issue, though feel free to continue discussion below if you still have questions

**Closed by pes10k** 2021-07-21 20:47 UTC

**Comment by coolharsh55** [comment] 2021-07-22 10:27
You've asked follow-up questions, but closed the issue. Does this mean a decision has been made and you don't want further feedback on this? 

Regardless - Yes, I have use-cases and practical reasons for why I discuss values. Right now GPC has a single interpretation based on CCPA (legally enforceable) and GDPR (legal interpretation). In the EU, there is no notion of 'sell' data or restricting only third parties from 'selling data' - though where consent is used the ability to withdraw that consent to _share_ data with third parties must exist separate from other consent matters. So 'sell' and 'share' are two distinct activities when it comes to how GPC is applied. The 'right to object' is separate and distinct from 'withdrawing consent'. 

Rather than saying `GPC: 1` means all of these - which is problematic because it doesn't provide separation between all of these, GPC can be used to express not preferences, but 'rights'. So `GPC: 1` can mean do not share data with third parties on the basis of consent, object where legitimate interest is used for such sharing; and other values can assist in applying other rights.

For example; `GPC: 3` can mean share data for research (non-commercial entities) purposes. `GPC: 5` can mean apply objection to first parties legitimate interests as well. `GPC: 7` can mean apply objection to profiling and automated decision making. Values can be combined e.g. by using primes and combinations (e.g. 3 means 1 x 3, 15 means 1 x 3 x 5 applies and so on) or using bit values. Multiple values are feasible since GPC is transmitted not as a boolean but as an integer/character.

**Comment by coolharsh55** [comment] 2021-07-22 10:43
As for fingerprinting, IMHO it is not a good strategy to say lets not give users more privacy management and preferences because it _may_ be used for fingerprinting. There *are* separate 'preferences' to mange: giving consent, withdrawing consent, consent for sharing data, consent for sharing data with first party only, consent for sharing data with third parties only, objecting to legitimate interest, objecting to profiling, objecting to direct marketing, objecting to automated decisions. GPC choosing only a few specific ones based on how CCPA works may not represent the best interests of users across the globe. If this is to be a web standard, then it must work for all web users. It has to address 'basic' concepts - either by making them explicit in the spec or by relying on their commonality.

Like the previous comment says, EU doesn't have 'sell' as a data processing activity. Saying GPC prohibits sharing of data to any 'third party' is not enough - what is a third party also differs by jurisdiction! E.g. processors may or may not be third parties. Similarly, GPC doesn't consider what happens when data is 'shared' by joint-controllers - which is again a jurisdiction specific concept. So is the right to object. What happens when GPC implementation doesn't fulfill jurisdiction-based necessities such as these? Do we again invent a separate signal for these items? See [ADPC](https://www.dataprotectioncontrol.org/spec/). 

As for inferring jurisdiction, the website is _needed_ to infer these, e.g. to see what laws to comply with. If serving to EU users, GDPR must be complied with. If serving to California users, CCPA must be complied with. GPC is not a barrier to inferring jurisdiction - this information is already present in other inferrable data: IP addresses and language/region/timezone settings.

**Comment by coolharsh55** [comment] 2021-07-22 10:51
Regarding `GPC: 0` being the same as not sending a GPC signal is incorrect. `GPC: 0` *must* have an interpretation, otherwise any website, browser, user-agent that doesn't support GPC can assume user has set `GPC: 0` and claim data sharing is permitted!

| I expect a Sec-GPC: 0 value would be the same thing as sending nothing. If a site wants to know that the user turned off GPC in response to the page's request, they can already do though a session cookie (or similar) and seeing that the GPC signal is no longer sent. - [pes10k](https://github.com/globalprivacycontrol/gpc-spec/issues/22#issuecomment-884488714)

Arguing that a cookie is needed to signal GPC is no longer set is not a good design IMHO. So you're asking the website to store cookies representing the GPC state, and then later checking that cookie each time there's no GPC signal to infer if the user has turned GPC off? Why not just have GPC specify its state? What if I actually want to enable sharing data with third parties because its an actually beneficial use-case and I believe they're good and not data vampires? E.g. I want to share that I read a news story posted on some other site to the actual news publisher. Yes, I want them to track how many views their story got, but they don't profile me. This is sharing data with third parties that would be prohibited by GPC. Just because the current malicious activity of third party data sharing is bad doesn't mean there are zero useful cases where data sharing is beneficial.

**Comment by SebastianZimmeck** [comment] 2021-07-24 16:29
These are important points. For the time being, I think a binary signal will serve us well. Keeping it simple will make GPC easy to implement and to use. Essentially, it is a question for the user: do you want privacy? Yes or no.

@darobin wrote up in a [blog post](https://berjon.com/gpc-under-the-gdpr/) how GPC can be interpreted under the GDPR. For the recipient of a GPC signal in a GDPR jurisdiction it would be reasonable to interpret it to mean that the user withdraws consent and objects to the processing of their data to the extent it is based on legitimate or public interest. This way GPC can be fitted in different jurisdictions allowing regulators to attach meaning under their local laws.

**Comment by coolharsh55** [comment] 2021-07-24 22:39
Thanks. I wrote up on some of the considerations of GPC and GDPR [here](https://harshp.com/research/blog/gpc-gdpr-can-it-work) before Robin's post, so its my opinion rather than a response. I agree with Robin's post, and the spirit of GPC. But disagree that there is a straightforward interpretation in GDPR. There isn't, and the GPC spec should, IMHO, clarify what it should mean under GDPR rather than asking the law to interpret how the signal may be used for it. Its the equivalent of the chicken and egg problem - what comes first? In this case, between the signal and the law, the signal must come first.

As to why different values: How can the same signal convey different actions depending on jurisdiction? In CCPA, it restricts 'selling' (Do Not Sell) which when compared with GDPR, is probably equivalent to restriction of sharing data with third parties for commercial(isation) purposes. GDPR does not have a notion of 'selling data', nor does it make a distinction between for-profit purposes. Yet, the [GPC mentions](https://globalprivacycontrol.github.io/gpc-spec/#legal-effects) that:

> The GPC signal is intended to convey a general request that data controllers limit the sale or sharing of the user's personal data to other data controllers ([GDPR] Articles 7 & 21).

So already here there is an incompatibility between what the signal means depending on whether one happens to be in California or EU (sell vs share). Furthermore,  'third parties', as I mentioned before, are also different concepts across jurisdictions. So the spec should also clarify these because otherwise it remains incompatible with jurisdictional laws. The law can, at most, say signal should be respected in matters of consent or preferences (e.g. ePrivacy Regulation in EU). However, the signal/spec itself must be clear on what its interpretation means. For GPC, CCPA provides an enforceable basis for simply stating 'do not sell', which already exists codified in law. Unfortunately, this has no equivalent in GDPR. There is no 'do not share' signal or right. A generalised  solution would be saying:

> GPC is "a signal that indicates restriction of data sharing with third parties" - and keeping the legal basis (e.g. consent) outside this. Thus, when the signal is active/set, and the legal basis happens to be consent, it indicates the data subject has chosen not to consent to such sharing, or is withdrawing the consent. If the legal basis is legitimate interest, they object to such sharing. This is much clearer IMHO than saying "withdraws consent" without being specific as to which consent, or why. 

If adopted, this then creates an incompatibility between 'do not sell' and 'do not share' (as above) because sell and share do not mean the same thing. And given that GPC is already enforceable in CCPA, its intention and interpretation cannot be changed retrospectively. That's why the original proposal for multiple values as an exploration of how to resolve this.

**Comment by asoltani** [comment] 2021-07-24 23:13
Thanks for the input @coolharsh55 
We'll take it under advisement.

**Comment by michael-oneill** [comment] 2021-07-25 15:25
The server could indicate what the signal means to it (i.e. taking into account what legal jurisdiction etc.), either in the gpc.json resource or preferably in a response header. 
This removes some of the fingerprinting risk.
Regulators in particular jurisdictions could mandate the response,
